
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.zune-core]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.zune-jpeg]]
version = "0.4.19"
criteria = "safe-to-deploy"
